### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by jadav1982** [nitinkumarmishra/angular2-app#1]
I have used NPM 3.10.3 and Node v6.3.1.

C:\temp\test\SB-Admin-BS4-Angular-2>npm start

> angular2-app@0.0.0 start C:\temp\test\SB-Admin-BS4-Angular-2
> gulp serve.dev --color

[16:10:08] Requiring external module ts-node/register
(node:2868) fs: re-evaluating native module sources is not supported. If you are
 using the graceful-fs module, please update it to a more recent version.
[16:11:14] Loading tasks folder C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\
seed
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\build.assets.dev
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\build.assets.prod
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\build.bundles.app
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\build.bundles
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\build.docs
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\build.html_css
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\build.index.dev
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\build.index.prod
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\build.js.dev
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\build.js.e2e
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\build.js.prod
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\build.js.test
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\build.js.tools
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\check.versions
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\clean.all
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\clean.dev
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\clean.prod
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\clean.tools
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\copy.js.prod
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\css-lint
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\e2e
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\generate.manifest
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\karma.start
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\serve.coverage
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\serve.docs
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\server.prod
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\server.start
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\tslint
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\watch.dev
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\watch.e2e
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\watch.test
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\seed
\webdriver
[16:11:14] Loading tasks folder C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\
project
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\proj
ect\build.fonts
[16:11:14] Registering task C:\temp\test\SB-Admin-BS4-Angular-2\tools\tasks\proj
ect\sample.task
[16:11:14] Using gulpfile C:\temp\test\SB-Admin-BS4-Angular-2\gulpfile.ts
[16:11:14] Starting 'serve.dev'...
[16:11:14] Starting 'build.dev'...
[16:11:14] Starting 'tslint'...
[16:11:28] Finished 'tslint' after 14 s
[16:11:28] Starting 'build.assets.dev'...
[16:11:33] Finished 'build.assets.dev' after 4.71 s
[16:11:33] Starting 'build.fonts'...
[16:11:36] Finished 'build.fonts' after 3.67 s
[16:11:36] Starting 'build.html_css'...
[16:11:42] 'build.html_css' errored after 5.56 s
[16:11:42] Error: Missing binding C:\temp\test\SB-Admin-BS4-Angular-2\node_modul
es\gulp-sass\node_modules\node-sass\vendor\win32-x64-48\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit
with Node.js 6.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 4.x

This usually happens because your environment has changed since running `npm ins
tall`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at Object.<anonymous> (C:\temp\test\SB-Admin-BS4-Angular-2\node_modules\gulp
-sass\node_modules\node-sass\lib\index.js:15:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\temp\test\SB-Admin-BS4-Angular-2\node_modules\gulp
-sass\index.js:187:21)
    at Module._compile (module.js:541:32)
[16:11:42] 'serve.dev' errored after 28 s
[16:11:42] Error in plugin 'run-sequence'
Message:
    An error occured in task 'build.html_css'.
[16:11:42] 'build.dev' errored after 28 s
[16:11:42] Error in plugin 'run-sequence'
Message:
    An error occured in task 'serve.dev'.
[16:11:42] 'build.dev' errored after 28 s
[16:11:42] Error in plugin 'run-sequence'
Message:
    An error occured in task 'build.html_css'.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-app@0.0.0 start: `gulp serve.dev --color`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-app@0.0.0 start script 'gulp serve.dev --color'.

npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-app package,

npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve.dev --color
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\temp\test\SB-Admin-BS4-Angular-2\npm-debug.log

C:\temp\test\SB-Admin-BS4-Angular-2>

**Comment by jadav1982** [comment]
i have updated gulp-sass and it's working
